#!/bin/bash
#
# INSTALL PocketFEATURE
# =====================
# 
# RUNNING THIS SCRIPT WILL ATTEMPT TO AUTOMATICALLY INSTALL
# sudo ./INSTALL
#
# Installing PocketFEATURE requires installing two packages:
# pyFEATURE, a set of wrappers and tools for working with FEATURE data
# and PocketFEATURE itself.
#
# Both installations are simple Python setup scripts.
#
# First install pyFEATURE:
# ------------------------
#
# $ cd pyFEATURE
# $ sudo python setup.py install
# $ cd ../
# 
# Second install PocketFEATURE:
# -----------------------------
#
# $ cd PocketFEATURE
# $ sudo python setup.py install
# $ ../
#
# Then run a test case:
#
#

if [ ! -z $1 ]; then
	ALIGN="--alignment $1"
fi

echo "Cleaning up old versions"
pip uninstall pyFEATURE PocketFEATURE

set -e

if [ ! -z $VIRTUAL_ENV -a ! -d $VIRTUAL_ENV/lib/python2.7/site-packages/numpy/core/include ]; then
    echo "Fixing Numpy/Virtualenv issues"
    pip install --force-reinstall --upgrade numpy
fi

echo "Checking for FEATURE"
if [ ! $( which featurize ) ]; then
    echo "Warning: featurize not found in PATH. Likely to fail"
    echo "Press Enter to continue..."
    read
fi

echo "Checking FEATURE environment"
if [ -z $FEATURE_DIR ]; then
    echo "Warning: FEATURE_DIR not set. PocketFEATURE will try to guess"
    echo "Note: This can also be solved by calling PocketFEATURE programs"
    echo "      with the --feature-dir argument"
    echo "Press Enter to continue..."
    read
fi
    

echo "INSTALLING pyFEATURE"
cd pyFEATURE
rm -vrf *.egg-info
python setup.py install
cd ../

echo "INSTALLING PocketFEATURE"
cd PocketFEATURE
rm -vrf *.egg-info
python setup.py install
cd ../

echo "RUNNING SANITY TEST"
export PDB_DIR="./data"
export DSSP_DIR="./data"
run_pf data/1qhx.pdb data/1qrd.pdb \
       -b data/background.ff \
       -n data/background.coeffs \
       --pymolA=/tmp/1qhx.py \
       --pymolB=/tmp/1qrd.py \
       --pdb-dir=data \
       --dssp-dir=data \
       $ALIGN

echo "Attempting to visualize"
if [ $( which pymol ) ]; then
    pymol -l /tmp/1qhx.py &
    pymol -l /tmp/1qrd.py &
else
    echo "PyMol not found in PATH. Cannot display alignment"
    echo "pymol -l /tmp/1qhx.py &"
    echo "pymol -l /tmp/1qrd.py &"
fi
